### ISSUE TITLE
ModuleNotFoundError: No module named 'dhooks'

### ISSUE THREAD

**Issue by jaredmarcus** [kyb3r/dhooks#40]
Although this issue is a newbie issue, on my end it's not. I have checked that it's installed using the right version of pip for python 3
`pip3 install dhooks`
and it returns that it's installed already. So I double checked using 
`pip3 list`
and it spits back a whole list showing dhooks is at 1.1.4
I am using python3 for my project and can't seem to figure out what the issue is.

Update: I found out that this issue is only within an IDE, when I execute a command to run this script in a python IDE shell it runs perfectly fine.

**Comment by DEtermination21** [comment]
I have the same problem I installed dhooks using 

> python install dhooks 

and I am sure that it is installed on my computer because when I try to install it again I get a Requirement already satisfied error but whenever I try doing a python program using 

> from dhooks import Webhook

and it returns

> ModuleNotFoundError: No module named 'dhooks'

and I am not able to do anything to fix it. I tried opening the file with pycharm that I use for school and I am still getting the same error. Please tell me how you fixed it

**Comment by msr8** [comment]
You both are probably using the wrong version of python. Try to run the program via the command prompt using `python [pyfile]` and if the error still shows, do `python -m pip install dhooks` and then run the program again via cmd (command prompt)
